name: Build & Deploy Docs
on:
  push:
    branches: [ main ]
    paths:
      - "openapi/**"
      - "guides/**"
      - "webhooks/**"
      - "website/**"
      - "README.md"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with: 
          node-version: "20"
      - run: cd website && npm ci && npm run build
      - uses: actions/upload-pages-artifact@v4
        with: 
          path: website/build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4